version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
      - /app/node_modules

    container_name: manga-scraping-app
    ports:
      - ${PORT}:${PORT}
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      PORT: ${PORT}